### ISSUE TITLE
some user endpoints requiring auth

### ISSUE THREAD

**Issue by dillon** [ivangreene/arena-js#11]
Docs say users/:id/channels shouldn't require auth, but may of the users/ endpoints do, even for public info.
[https://dev.are.na/documentation/users#Block59785](https://dev.are.na/documentation/users#Block59785)

[https://api.are.na/v2/users/10097/channels](https://api.are.na/v2/users/10097/channels)

`{"code":401,"message":"Unauthorized","description":"Invalid credentials."}`

**Comment by broskoski** [comment]
Thanks, fixed in https://github.com/ivangreene/arena-js/pull/6
