### ISSUE TITLE
Options not being passed.

### ISSUE THREAD

**Issue by callil** [ivangreene/arena-js#5]
Always getting 25 results no matter what I pass into the query.

Testing from the demo code in the readme.

```
arena.channel('arena-influences').contents({ page: 1, per: 3 })
  .then(content => {
    console.log(content.length)
  })
  .catch(err => console.log(err));
```

If I dig into the axios request - everything looks to be included, but no dice. Tested in choo and CRA.

**Comment by oilstel** [comment]
Hmm yeah this is happening to me too. Any luck from when you posted @callil?

**Comment by yannbolliger** [comment]
I confirm this issue. The problem stems from here:
https://github.com/ivangreene/arena-js/blob/cab291722e2a704a38604960b219b69223d549f5/index.js#L43
The options are not passed separately.

**Comment by cyruskorn** [comment]
Same here. Anybody working on a fix?

**Comment by callil** [comment]
Ok digging into this a bit more. I see that axios parse the options as follows: `page=2&per=15` whereas the API docs on are.na seem to want it formatted like this `page=2&amp;per=15` 

I'm note sure this is the cause but it's the only weird thing I can find so far

**Comment by callil** [comment]
ok figured it out - we must pass the options as params not data into the request. data can only be used for POST/PUT requests. So instead of serializing the options and passing them we have to just pass em as params. Still looking into the implications for other request types? Anyway PR is here: https://github.com/ivangreene/arena-js/pull/21
