### ISSUE TITLE
Axios vulnerability

### ISSUE THREAD

**Issue by mwvd** [ivangreene/arena-js#9]
Axios `^0.17.1` dependency is out of date, and running `$ yarn/npm audit` throws a [moderate vulnerability](https://www.npmjs.com/advisories/880). ⤵

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.18.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ axios                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/880                         │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

From the [npm advisory](https://www.npmjs.com/advisories/880) ⤵

> ### Overview
>
> Versions of axios prior to 0.18.1 are vulnerable to Denial of Service. If a request exceeds the maxContentLength property, the package prints an error but does not stop the request. This may cause high CPU usage and lead to Denial of Service.
> 
> ### Remediation
> 
> Upgrade to 0.18.1 or later.
> 
> ### Resources
> 
> - [Github Issue](https://github.com/axios/axios/issues/1098)
> - [Snyk Report](https://snyk.io/vuln/SNYK-JS-AXIOS-174505)

Think this might be also be getting caught by some twitchy anti-virus software, but will update when I figure out.

**Comment by broskoski** [comment]
Closed in https://github.com/ivangreene/arena-js/pull/16
